name: Create and deploy DACPAC

on: 
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
  build:
    name: Build DACPAC
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build DACPAC
        run: msbuild 'DatabaseMigrationsTest.sln' /t:build
        #run: msbuild 'DatabaseMigrationsTest.sln' /p:TargetFrameworkVersion=v4.7.1 /p:DSP=Microsoft.Data.Tools.Schema.Sql.SqlAzureV12DatabaseSchemaProvider

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dacpac-artifact
          path: '*\bin\Debug\**.dacpac'

