name: Create and deploy ISPAC

on: 
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
  build:
    name: Build ISPAC
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSIS DevOps Tools
        uses: jonlabelle/setup-ssis-devops-tools@v1

      - name: Build ISPAC
        run: SSIBBuild.exe 'SampleSSISProject\SampleSSISProject.dtproj'
        #run: msbuild 'DatabaseMigrationsTest.sln' /p:TargetFrameworkVersion=v4.7.1 /p:DSP=Microsoft.Data.Tools.Schema.Sql.SqlAzureV12DatabaseSchemaProvider

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: isapac-artifact
          path: '*\bin\Debug\**.dacpac'

